### ISSUE TITLE
timeout waiting for merge when actually waiting for CI

### ISSUE THREAD

**Issue by John-Colvin** [smarkets/marge-bot#204] opened 2019-06-12 15:19 UTC
I have "Merge commit with semi-linear history" set.
I create a MR.
CI starts running.
I assign to MargeBot.
It sets "merge when pipeline succeeds" and then after 5 minutes unassigns itself saying "I couldn't merge this branch: It is taking too long to see the request marked as merged!" but leaves the automatic merge in place.

If this happens for multiple MRs then obviously only one will be merged and the others will sit unmerged.

**Comment by B-Michelsen** [comment] 2019-07-11 07:22
Hi @John-Colvin 
I think I am seeing a similar issue.
For my case, the issue seems to be that my working model is fork based.
So I have my main repo with my master branch.
Forked the main repo and created my new branch.
Created a MR on the main repo, to merge my branch in to the master branch.
CI started automatically.
Assigned to Marge and after 5 minutes I get the same message.

After a bit of research, I think I found the cause for this issue.
in marge/single_merge_job.py it will only wait for the CI, if this condition is true:
`if source_project.only_allow_merge_if_pipeline_succeeds:`
Which means that it checks if this option is set on the source project of the MR (ie. my fork, which might not have the same configuration as the main repo).
To me it seems like it should really check the options in the target repository, since this is where I am merging stuff in to, so this is also where the CI will run on.

**Closed** 2019-07-16 10:41 UTC

**Comment by John-Colvin** [comment] 2019-07-16 14:46
I'm not sure this is resolved. My problem exists when source and target project are the same.

**Comment by JaimeLennox** [comment] 2019-07-16 15:22
Do you have `Only allow merge requests to be merged if the pipeline succeeds` checked in your project settings?

**Comment by John-Colvin** [comment] 2019-07-16 16:23
No

**Comment by JaimeLennox** [comment] 2019-07-16 16:25
I think you need this enabled.
