### ISSUE TITLE
Marge should comment on/move to the next PR when there are other assignee's

### ISSUE THREAD

**Issue by james-ennis** [smarkets/marge-bot#214] opened 2019-07-09 14:45 UTC
## Description of the bug
We've just had an inactive marge-bot which was due to the fact that one of our PRs had two assignee's: Marge and the developer.

During the inactive time, several other PR's became mergable and were assigned to Marge. However, Marge remained inactive and the PR's were not merged.

From looking at the debug data, Marge was looking at the first PR and not doing anything because herself and the developer were assigned. After this check, Marge immediately went to check the next repo.

## Expected behaviour
Marge should comment on the PR with two assignee's and say that she can't do anything if there are two or more assignee's **or** she should just merge it.

If the former, Marge could try the next Marge-assigned PR.

**Comment by thinkl33t** [comment] 2019-07-09 14:53
The specific warning triggered was:

```
2019-07-09 14:22:18,629 WARNING Skipping MR !1327: It is not assigned to me anymore!
```

This was happening every merge attempt against this repo

**Comment by thinkl33t** [comment] 2019-07-09 16:00
OK, Having dug a bit It looks like this should work in master - we are running the docker version where `:latest` is still on 0.8.1, so next release should fix it.

**Comment by bagage** [comment] 2019-07-10 09:22
Hopefully a new tag will be released, this bug is indeed blocking margebot from working as intended.

**Comment by JaimeLennox** [comment] 2019-07-10 16:44
0.9.0 has now been released. Please re-open if you believe this is still an issue.

You might also be interested to know that you can use the tag `:master` for the docker image, which follows the latest commit.

**Closed by JaimeLennox** 2019-07-10 16:44 UTC

**Comment by james-ennis** [comment] 2019-07-10 16:47
Thanks for the release @JaimeLennox!
