### ISSUE TITLE
docker image date stamped 1970

### ISSUE THREAD

**Issue by glensc** [smarkets/marge-bot#73] opened 2017-12-17 22:17 UTC
so weird:

```
# docker images|grep marge-bot
smarketshq/marge-bot                                0.5.0                          cbc2be3ebd0c        47 years ago        504MB
smarketshq/marge-bot                                latest                         22433019da23        47 years ago        276MB
```

they seem ok in dockerhub:
https://hub.docker.com/r/smarketshq/marge-bot/tags/

**Comment by jcpetruzza** [comment] 2017-12-18 00:40
I know it looks funny at first, but it is actually by design. We are using [Nix](https://nixos.org/nix/) to package  marge and, in particular, to generate the docker images we use for distribution (see e.g. [this article](http://lethalman.blogspot.co.uk/2016/04/cheap-docker-images-with-nix_15.html) for details). The latter means that the final images are relatively small, but more importantly reproducible: the image you download from docker-hub should be exactly the same as the one you would get if you were to run `make dockerize` locally.

For reproducibility to work, you need all timestamps in the image to be the same, regardless of when you build the image. The convention in Nix is to timestamp all the artifacts it builds with one-second-after-the-epoch and that is extended to the docker image.

I remember having a WTF-moment the first time I saw the `47 years ago` on a `docker images`, but I guess I got used to it now. Is there any actual problem with this convention, in your opinion?

**Comment by glensc** [comment] 2017-12-18 17:18
there's no functional problem, just clarity, i wanted to know how old image i was running (used `:latest` tag), and all images were "very old".

**Comment by jcpetruzza** [comment] 2017-12-22 18:42
I see. I imagine you can instead check the creation date of the container? I will close this one for now, but feel free to re-open.

**Closed by jcpetruzza** 2017-12-22 18:42 UTC
