### ISSUE TITLE
"branch cannot be merged" on freedesktop.org

### ISSUE THREAD

**Issue by anholt** [smarkets/marge-bot#263] opened 2020-06-29 16:02 UTC
Since a gitlab update, we've been seeing "branch cannot be merged" intermittently from marge.  One of our gitlab admins looked into it and concluded:

> Yeah, as suspected the culprit is Marge not doing the right thing:
> 
>> Note: Starting in GitLab 12.8, the mergeability (merge_status) of a merge request will be checked asynchronously when a request is made to this endpoint. Poll this API endpoint to get updated status. This affects the has_conflicts property as it is dependent on the merge_status. It’ll return false unless merge_status is cannot_be_merged.
> 
> Completing a pipeline will cause a MR to become mergeable, but not instantaneously. Marge assumes that the instant a pipeline reports complete, the MR will be mergeable. That's not actually true, since it still has to check for things like whether or not the head is a fast-forward, etc. This is done in a background job via Sidekiq.
The fix seems pretty straightforward: in Marge's job handling, after pipeline completion but before merging, it needs to poll on merge_status and watch it go green. I looked at it briefly this morning, but it involved NixOS and that pushed it over the time budget I have right now. If someone wants to pick up updating Marge then I'm happy to get it deployed.

**Comment by fooishbar** [comment] 2020-06-30 10:34
The missing link was to the GitLab API docs, specifically the [get single MR endpoint](https://docs.gitlab.com/ee/api/merge_requests.html#get-single-mr) where the quote comes from.

**Comment by snim2** [comment] 2020-07-01 12:53
I've also been seeing this on gitlab.com since 12.8. Reassigning Marge usually works, which would make sense given this explanation.

**Comment by snim2** [comment] 2020-07-28 15:36
Any thoughts on how a fix for this would work? Maybe poll the endpoint with an exponential back-off?

**Comment by fooishbar** [comment] 2020-07-28 15:45
Yeah, I think that's the one. Maybe linear rather than exponential, since it certainly should complete quickly, and if the issue is background jobs (to recheck the MR status) aren't completing quickly, the poll shouldn't impede their progress as they're just a quick read of a Redis-cached property, run separately to the Sidekiq jobs (not necessarily even on the same node).

**Closed** 2020-11-11 09:16 UTC
