### ISSUE TITLE
400 BadRequest when unassigning merge request on gitlab.com

### ISSUE THREAD

**Issue by veeg** [smarkets/marge-bot#131] opened 2018-09-12 12:29 UTC
While testing the adoption and functionality of marge-bot, I stumbled upon a few issues.

1) If no CI pipeline is configured for the repository, the CI job will timeout after 15 minutes and attempt to unassign itself. I suspect this is the assumption for marge-bot, by design. However, I could not find any mention of this requirement. I wanted to use marge-bot for all our repositories, even for those which requires no build or test, to have a uniform merge request flow within our company. If this is indeed a requirement by marge-bot, I'd suggest documenting it in the README.

2) The unassignment failed horribly with a bad request in the gitlab response. I can only reason that gitlab changed their API endpoint, since assignee_id is provided?

```
2018-09-12 11:27:45,863 INFO Running git -C /tmp_c2tlfpl/tmpcwrgaa18 branch -D test-marge
2018-09-12 11:27:45,878 INFO Commit id to merge 'e6a25096ef69d3aa85a03b208740dd4b404065c1' (into: '31cbb2a1e19f5f5be96bacb9c5730d8e8ca0f376')
2018-09-12 11:27:51,986 INFO Waiting for CI to pass for MR !1
2018-09-12 11:27:53,042 WARNING No pipeline listed for e6a25096ef69d3aa85a03b208740dd4b404065c1 on branch test-marge
2018-09-12 11:27:53,042 WARNING Suspicious CI status: None

...

2018-09-12 11:42:44,432 WARNING No pipeline listed for e6a25096ef69d3aa85a03b208740dd4b404065c1 on branch test-marge
2018-09-12 11:42:44,432 WARNING Suspicious CI status: None
2018-09-12 11:42:54,436 WARNING I couldn't merge this branch: CI is taking too long.
2018-09-12 11:42:54,436 INFO Unassigning from MR !1
Traceback (most recent call last):
  File "/nix/store/77wrcwqx8p2wbw3n0v5v4lsvh7bwn01w-python3.6-marge-0.7.0/lib/python3.6/site-packages/marge/single_merge_job.py", line 24, in execute
    self.update_merge_request_and_accept(approvals)
  File "/nix/store/77wrcwqx8p2wbw3n0v5v4lsvh7bwn01w-python3.6-marge-0.7.0/lib/python3.6/site-packages/marge/single_merge_job.py", line 69, in update_merge_request_and_accept
    self.wait_for_ci_to_pass(merge_request, actual_sha)
  File "/nix/store/77wrcwqx8p2wbw3n0v5v4lsvh7bwn01w-python3.6-marge-0.7.0/lib/python3.6/site-packages/marge/job.py", line 160, in wait_for_ci_to_pass
    raise CannotMerge('CI is taking too long.')
marge.job.CannotMerge: CI is taking too long.

```

During handling of the above exception, another exception occurred:

```
Traceback (most recent call last):
  File "/nix/store/77wrcwqx8p2wbw3n0v5v4lsvh7bwn01w-python3.6-marge-0.7.0/bin/.marge.app-wrapped", line 4, in <module>
    marge.app.main()
  File "/nix/store/77wrcwqx8p2wbw3n0v5v4lsvh7bwn01w-python3.6-marge-0.7.0/lib/python3.6/site-packages/marge/app.py", line 261, in main
    marge_bot.start()
  File "/nix/store/77wrcwqx8p2wbw3n0v5v4lsvh7bwn01w-python3.6-marge-0.7.0/lib/python3.6/site-packages/marge/bot.py", line 41, in start
    self._run(repo_manager)
  File "/nix/store/77wrcwqx8p2wbw3n0v5v4lsvh7bwn01w-python3.6-marge-0.7.0/lib/python3.6/site-packages/marge/bot.py", line 59, in _run
    projects,
  File "/nix/store/77wrcwqx8p2wbw3n0v5v4lsvh7bwn01w-python3.6-marge-0.7.0/lib/python3.6/site-packages/marge/bot.py", line 97, in _process_projects
    self._process_merge_requests(repo_manager, project, merge_requests)
  File "/nix/store/77wrcwqx8p2wbw3n0v5v4lsvh7bwn01w-python3.6-marge-0.7.0/lib/python3.6/site-packages/marge/bot.py", line 164, in _process_merge_requests
    merge_job.execute()
  File "/nix/store/77wrcwqx8p2wbw3n0v5v4lsvh7bwn01w-python3.6-marge-0.7.0/lib/python3.6/site-packages/marge/single_merge_job.py", line 31, in execute
    self.unassign_from_mr(merge_request)
  File "/nix/store/77wrcwqx8p2wbw3n0v5v4lsvh7bwn01w-python3.6-marge-0.7.0/lib/python3.6/site-packages/marge/job.py", line 166, in unassign_from_mr
    merge_request.assign_to(author_id)
  File "/nix/store/77wrcwqx8p2wbw3n0v5v4lsvh7bwn01w-python3.6-marge-0.7.0/lib/python3.6/site-packages/marge/merge_request.py", line 138, in assign_to
    {'assignee_id': user_id},
  File "/nix/store/77wrcwqx8p2wbw3n0v5v4lsvh7bwn01w-python3.6-marge-0.7.0/lib/python3.6/site-packages/marge/gitlab.py", line 55, in call
    raise error(response.status_code, err_message)
marge.gitlab.BadRequest: (400, {'error': 'assignee_id, description, labels, milestone_id, remove_source_branch, state_event, target_branch, title, discussion_locked, squash are missing, at least one parameter must be provided'})

```

**Comment by JaimeLennox** [comment] 2018-09-15 09:40
1. This is due to this setting on GitLab: https://gitlab.com/help/user/project/merge_requests/merge_when_pipeline_succeeds#only-allow-merge-requests-to-be-merged-if-the-pipeline-succeeds; if you have this enabled, then Marge will expect a pipeline to exist, so she can wait for it to complete; I'm not sure it's possible for Marge to detect whether pipelines are actually in use if this setting has been enabled. Perhaps we should be clearer about documenting this behaviour though.
2. This is strange - what version of GitLab are you using? Just passing `assignee_id` should be sufficient for this.

**Comment by veeg** [comment] 2018-09-19 06:58
1) Thank you for that explanation. Of course this setting was enabled. Learn something every day.

2) This was against gitlab.com

**Comment by JaimeLennox** [comment] 2018-09-22 11:34
Thanks, I was able to recreate the issue on gitlab.com - I will debug the problem.

**Comment by JaimeLennox** [comment] 2018-09-22 15:44
Ok, I was able to reproduce this, but now I cannot. GitLab seems to have released a new version very recently, so I imagine this included a fix, and hence this was a problem on their side. @veeg can you confirm that the issue no longer occurs?

**Comment by JaimeLennox** [comment] 2018-09-29 09:00
Well this was fun to find. It turns out if you are using "http://gitlab.com" as the `gitlab-url`, then it fails with this error; if you use "https://gitlab.com" (i.e. the secure url), then it proceeds correctly. I imagine this is due to a redirect on GitLab's side which doesn't propagate the JSON body.

@veeg can you check to see if this is your issue?

**Comment by veeg** [comment] 2018-10-02 12:00
This was indeed the issue! Thanks!

**Closed** 2018-10-02 12:50 UTC
